### PR TITLE
Fix SSE

### PR DESCRIPTION
**Pull request by ClassicOldSong**

### CODE REVIEW

**Comment by juzeon** [comment]
Hello. It seems that the change causes network-related issues. The operation of add_token takes 3 to 10 seconds in my environment. Therefore, calling add_token every time may not be an optimal way. Could you please find a better solution, such as setting this as optional?

**Comment by ClassicOldSong** [comment]
This is a fallback routine. It won't happen every time a message is sent.
When the API server restarts, the Go server won't re-add the token. So this
will only happen when the API server gets restarted.

居正 ***@***.***> 于2023年6月5日周一 10:22写道：

**Comment by ClassicOldSong** [comment]
What's more, `poe-api` was updated with a faster and more stable response
time. You may consider upgrading `poe-api` in your environment.

Yukino Song ***@***.***> 于2023年6月5日周一 10:48写道：

**Comment by juzeon** [comment]
Thank you for your clarification. Please accept my apologies for the misunderstanding. I'm working on the merge right now.

**Pull request merged**
